name: Mobile APK Generator
on: [workflow_dispatch, push]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Project Dependencies
        run: npm install

      - name: Build Web Version
        run: npm run build:fast

      - name: Setup Java (Updated to 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # Теперь точно совпадет с требованиями Capacitor

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Add Capacitor and Build APK
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          if [ -d "dist" ]; then
            WEB_DIR="dist"
          else
            WEB_DIR="."
          fi
          npx cap init "SpessaFontMobile" "com.my.spessafont" --web-dir $WEB_DIR
          npx cap add android
          npx cap copy
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: SpessaFont-Mobile-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
